tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "bat"
brew "bitwarden-cli"
brew "buku"
brew "cask"
brew "diff-so-fancy"
brew "exa"
brew "fd"
brew "fnm"
brew "fzf"
brew "gh"
brew "git-flow-avh"
brew "git"
brew "gitlint"
brew "gnupg"
brew "gnutls"
brew "go"
brew "gpg"
brew "jq"
brew "mas"
# brew "maven"
# brew "neovim"
brew "openssl@3"
brew "pinentry-mac"
brew "ripgrep"
brew "thefuck"
brew "wget"
brew "zsh-completions"
# brew "watch"

# cask "firefox-developer-edition"
# cask "firefox"
cask "bitwarden"
cask "calibre"
cask "font-caskaydia-cove-nerd-font"
cask "freecad"
cask "gitkraken"
cask "guitar-pro"
cask "tuxguitar"
cask "google-chrome-canary"
cask "google-chrome-dev"
cask "google-chrome"
# cask "inkscape"
cask "insomnia"
cask "jetbrains-toolbox"
cask "iterm2"
# cask "logseq"
cask "microsoft-excel"
cask "obsidian"
cask "raycast"
# cask "rancher"
cask "thingsmacsandboxhelper"
cask "visual-studio-code"

# Install apps from the app store
mas "Day One", id: 1055511498
mas "Omnivore", id: 1564031042
mas "Things 3", id: 904280696
mas "Xcode", id: 497799835