# See this for more information:
# https://cbea.ms/git-commit/
# https://www.conventionalcommits.org/en/v1.0.0/
git:
  parseEmoji: true
customCommands:
  - key: "C"
    command: 'git commit -m "{{ .Form.emoji }} {{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}: {{ .Form.Description }} " -m  "{{ .Form.Body }}"'
    description: "Conventional Commit"
    context: "files"
    prompts:
      - command: gitmoji -l
        filter: ^(.*?) - (:.*?:) - (.*)$
        key: emoji
        labelFormat: "{{ .group_1 }} - {{ .group_3 }}"
        title: "Choose a gitmoji: "
        type: menuFromCommand
        valueFormat: "{{ .group_2 }}"
      - type: "menu"
        title: "Select the type of change you are committing."
        key: "Type"
        options:
          - name: "Feature"
            description: "a new feature"
            value: "feat"
          - name: "Fix"
            description: "a bug fix"
            value: "fix"
          - name: "Documentation"
            description: "Documentation only changes"
            value: "docs"
          - name: "Styles"
            description: "Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
            value: "style"
          - name: "Code Refactoring"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "Performance Improvements"
            description: "A code change that improves performance"
            value: "perf"
          - name: "Tests"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
          - name: "Builds"
            description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
            value: "build"
          - name: "Continuous Integration"
            description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
            value: "ci"
          - name: "Chores"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "Reverts"
            description: "Reverts a previous commit"
            value: "revert"
      - type: "input"
        title: "Enter the scope(s) of this change."
        key: "Scopes"
      - type: "input"
        title: "Enter the short description of the change. (If applied, this commit will...)"
        key: "Description"
      - type: "input"
        title: "Enter a longer description of the change."
        key: "Body"
      - type: "confirm"
        title: "Is the commit message correct?"
        body: "{{ .Form.emoji }} {{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}: {{ .Form.Description }} \n\n{{ .Form.Body }}"
  - key: "c"
    command: 'git cz'
    description: "commit with commitizen"
    context: "files"
    output: terminal
  - key: "r"
    command: 'npx cz --retry'
    description: "Retry commit"
    context: "files"
    output: terminal
